name: Enemies within ourselves
favicon: null
layout_spectrum: 0.577999014640227
typography_spectrum: 0.792048865929246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.07087615202181041
  lightness: 0.0788229051977396
  saturation: 0.14496629405766726
  rhythmicContrast: 0.8485767552629113
purpose: []
